package com.example.utils

object Localization {
    private val translations = mapOf(
        "fa" to mapOf(
            "app_title" to "صندوقچه امن LUF",
            "setup_wizard" to "تنظیمات اولیه صندوقچه",
            "setup_password_hint" to "یک رمز عبور امن انتخاب کنید (حداقل ۶ کاراکتر)",
            "setup_confirm_password" to "تکرار رمز عبور اصلی",
            "setup_biometric" to "فعال‌سازی ورود سریع با اثر انگشت (بیومتریک)",
            "setup_key_file_title" to "انتخاب فایل کلید ورود",
            "setup_key_file_desc" to "یک فایل دلخواه (مانند یک عکس، آهنگ یا سند) به عنوان کلید فیزیکی خود انتخاب کنید. ورود به برنامه تنها با باز کردن این فایل کلید از طریق گزینه \"باز کردن با LUF Vault\" امکان‌پذیر خواهد بود.",
            "setup_key_file_button" to "انتخاب فایل کلید امنیتی",
            "setup_key_file_selected" to "فایل کلید فعلی: %1\$s",
            "setup_permissions_title" to "مجوزهای دسترسی به فایل‌ها",
            "setup_permissions_desc" to "برای رمزگذاری، مخفی‌سازی و انتقال امن فایل‌ها، نیاز به دسترسی به حافظه دستگاه است.",
            "setup_permissions_button" to "تأیید و اعطای مجوز دسترسی",
            "setup_complete_button" to "ذخیره تنظیمات و خروج",
            "setup_success_msg" to "تنظیمات با موفقیت ذخیره شد. برای ورود به برنامه، کافی است فایل کلید انتخابی را پیدا کرده و با این برنامه باز کنید.",
            "login_enter_password" to "رمز عبور خود را وارد کنید",
            "login_password_placeholder" to "رمز عبور اصلی",
            "login_button" to "ورود به صندوقچه",
            "login_biometric_prompt" to "احراز هویت بیومتریک",
            "login_biometric_reason" to "اسکن اثر انگشت برای دسترسی به فایل‌ها",
            "login_incorrect_password" to "رمز عبور نادرست است! %1\$d تلاش دیگر تا قفل موقت.",
            "login_locked" to "برنامه به دلایل امنیتی قفل شد. زمان انتظار: %1\$s",
            "login_direct_attempt_msg" to "دسترسی مستقیم مسدود است!\nبرای ورود امن به صندوقچه، ابتدا فایل کلید خود را در دستگاه پیدا کرده و آن را با برنامه LUF Vault باز کنید.",
            "login_invalid_key_msg" to "فایل کلید انتخاب شده معتبر نیست یا با نسخه ذخیره شده مطابقت ندارد. امکان ورود وجود ندارد.",
            "close_app" to "خروج از برنامه",
            "tab_images" to "تصاویر",
            "tab_videos" to "ویدیوها",
            "tab_documents" to "اسناد",
            "tab_apk" to "برنامه‌ها",
            "tab_archives" to "فشرده",
            "tab_audio" to "صداها",
            "tab_others" to "سایر فایل‌ها",
            "search_placeholder" to "جستجوی فایل‌ها…",
            "empty_gallery_title" to "صندوقچه خالی است",
            "empty_gallery_desc" to "هیچ فایلی مخفی نشده است. با زدن دکمه + فایل‌های خود را به صورت رمزگذاری شده پنهان کنید.",
            "settings_title" to "تنظیمات گاوصندوق",
            "settings_general" to "تنظیمات عمومی و امنیتی",
            "settings_prevent_screenshots" to "محافظت در برابر اسکرین‌شات",
            "settings_prevent_screenshots_desc" to "غیرفعال‌سازی اسکرین‌شات در تمام بخش‌های برنامه",
            "settings_prevent_recordings" to "محافظت در برابر ضبط صفحه",
            "settings_prevent_recordings_desc" to "مسدود کردن امکان فیلم‌برداری از صفحه نمایش",
            "settings_biometrics" to "احراز هویت بیومتریک",
            "settings_biometrics_desc" to "استفاده از سنسور اثر انگشت برای ورود ایمن و سریع",
            "settings_security" to "امنیت و رمز عبور",
            "settings_change_password" to "تغییر رمز عبور اصلی",
            "settings_change_password_desc" to "تغییر رمز عبور ورود به گاوصندوق",
            "settings_lock_timeout" to "مدت زمان قفل امنیتی",
            "settings_lock_timeout_1m" to "۱ دقیقه",
            "settings_lock_timeout_5m" to "۵ دقیقه",
            "settings_lock_timeout_30m" to "۳۰ دقیقه",
            "settings_customization" to "شخصی‌سازی و ظاهر",
            "settings_theme" to "تم رنگی برنامه",
            "settings_theme_light" to "سفید (روشن)",
            "settings_theme_dark" to "سیاه (تاریک)",
            "settings_theme_system" to "پیش‌فرض سیستم",
            "settings_about" to "درباره برنامه",
            "settings_about_desc" to "مشخصات توسعه‌دهنده و مجوزهای نرم‌افزار",
            "made_by" to "طراحی و توسعه توسط luffy",
            "visit_github" to "مشاهده گیت‌هاب سازنده",
            "custom_app_name_label" to "نام دلخواه گاوصندوق",
            "custom_app_name_desc" to "نام نمایشی که در هدر بالای برنامه نشان داده می‌شود",
            "change_key_file" to "تغییر فایل کلید امنیتی",
            "change_key_file_desc" to "تغییر فایلی که به عنوان کلید برای ورود به برنامه عمل می‌کند",
            "change_key_file_success" to "فایل کلید امنیتی با موفقیت تغییر یافت.",
            "protection_active" to "امنیت فعال است",
            "protection_active_desc" to "تمامی فایل‌ها با الگوریتم قدرتمند AES-256 رمزگذاری شده‌اند.",
            "storage_usage" to "مصرف حافظه: %1\$s از کل %2\$s (%3\$d%%)",
            "vault_storage" to "کل حجم فایل‌های گاوصندوق: %1\$s",
            "sort_by_name" to "نام فایل",
            "sort_by_size" to "اندازه فایل",
            "sort_by_date" to "تاریخ افزودن",
            "delete_confirm_title" to "حذف دائمی فایل‌ها",
            "delete_confirm_desc" to "آیا از حذف دائم فایل‌های انتخاب شده اطمینان دارید؟ این عملیات به هیچ عنوان قابل بازگشت نیست.",
            "delete_button" to "حذف دائم",
            "cancel" to "انصراف",
            "import_files_title" to "افزودن فایل به گاوصندوق",
            "import_select_button" to "انتخاب فایل‌ها",
            "import_storage_info" to "فضای آزاد: %1\$s | فضای مورد نیاز: %2\$s",
            "import_insufficient_storage" to "فضای حافظه کافی نیست!",
            "import_option_copy" to "کپی فایل (نسخه اصلی در دستگاه باقی می‌ماند)",
            "import_option_move" to "انتقال فایل (نسخه اصلی کاملاً حذف می‌شود)",
            "import_progress" to "در حال انتقال و رمزگذاری فایل‌ها… %1\$d%%",
            "import_success" to "فایل‌ها با موفقیت رمزگذاری و وارد گاوصندوق شدند.",
            "export_title" to "خروج فایل از گاوصندوق",
            "export_button" to "رمزگشایی و انتقال به دستگاه",
            "export_progress" to "در حال انتقال و رمزگشایی فایل‌ها… %1\$d%%",
            "export_success" to "فایل‌ها با موفقیت رمزگشایی و به پوشه Downloads/LUF منتقل شدند.",
            "lang_label" to "زبان برنامه (Language)",
            "lang_fa" to "فارسی",
            "lang_en" to "English",
            "app_info_title" to "مشخصات گاوصندوق LUF",
            "app_info_desc" to "این اپلیکیشن پیشرفته به منظور پنهان‌سازی و رمزنگاری داده‌ها طراحی شده است. تمام اطلاعات با استفاده از کلید خصوصی منطبق بر فایل هویتی شما کدگذاری شده و از دیدرس هر نوع برنامه‌ای پنهان می‌ماند.",
            "prev_btn" to "قبلی",
            "next_btn" to "بعدی"
        ),
        "en" to mapOf(
            "app_title" to "LUF Secure Vault",
            "setup_wizard" to "Initial Setup Guide",
            "setup_password_hint" to "Enter a secure master password (min 6 chars)",
            "setup_confirm_password" to "Confirm Master Password",
            "setup_biometric" to "Enable Biometric Fingerprint (Recommended)",
            "setup_key_file_title" to "Select Security Key File",
            "setup_key_file_desc" to "Choose any file (image, audio, document) to act as a physical authentication key. The app can only be opened by sharing/opening this key file using LUF Vault.",
            "setup_key_file_button" to "Choose Key File",
            "setup_key_file_selected" to "Current key file: %1\$s",
            "setup_permissions_title" to "Storage Access Permissions",
            "setup_permissions_desc" to "Required to encrypt, hide, and safely transfer files on your device.",
            "setup_permissions_button" to "Grant Storage Access",
            "setup_complete_button" to "Save & Exit",
            "setup_success_msg" to "Setup completed successfully. To log in next time, find your key file and open it with this app.",
            "login_enter_password" to "Enter Your Password",
            "login_password_placeholder" to "Master Password",
            "login_button" to "Unlock Vault",
            "login_biometric_prompt" to "Biometric Authentication",
            "login_biometric_reason" to "Scan your fingerprint to unlock secure files",
            "login_incorrect_password" to "Incorrect password! %1\$d attempts remaining before lockout.",
            "login_locked" to "Locked for security reasons. Wait duration: %1\$s",
            "login_direct_attempt_msg" to "Direct Access Restricted!\nTo open the vault securely, locate your key file and open it using LUF Vault (Open With).",
            "login_invalid_key_msg" to "The selected file is not a valid key or does not match. Access Denied.",
            "close_app" to "Exit App",
            "tab_images" to "Images",
            "tab_videos" to "Videos",
            "tab_documents" to "Documents",
            "tab_apk" to "Apps",
            "tab_archives" to "Archives",
            "tab_audio" to "Audio",
            "tab_others" to "Others",
            "search_placeholder" to "Search files…",
            "empty_gallery_title" to "Vault is Empty",
            "empty_gallery_desc" to "No secured files yet. Click the + button to encrypt and hide your private files.",
            "settings_title" to "Vault Settings",
            "settings_general" to "General & Security Settings",
            "settings_prevent_screenshots" to "Screenshot Protection",
            "settings_prevent_screenshots_desc" to "Block taking screenshots inside the app",
            "settings_prevent_recordings" to "Screen Capture Protection",
            "settings_prevent_recordings_desc" to "Block screen recording to secure visual content",
            "settings_biometrics" to "Biometric Login",
            "settings_biometrics_desc" to "Use fingerprint sensor for ultra-fast unlocking",
            "settings_security" to "Authentication & Keys",
            "settings_change_password" to "Change Master Password",
            "settings_change_password_desc" to "Modify the vault's main unlock password",
            "settings_lock_timeout" to "Lockout Duration",
            "settings_lock_timeout_1m" to "1 Minute",
            "settings_lock_timeout_5m" to "5 Minutes",
            "settings_lock_timeout_30m" to "30 Minutes",
            "settings_customization" to "Customization & Theme",
            "settings_theme" to "App Theme Mode",
            "settings_theme_light" to "White (Light)",
            "settings_theme_dark" to "Black (Dark)",
            "settings_theme_system" to "System Default",
            "settings_about" to "About Application",
            "settings_about_desc" to "Developer info & software specifications",
            "made_by" to "Designed & Developed by luffy",
            "visit_github" to "Visit Developer's GitHub",
            "custom_app_name_label" to "Custom Vault Name",
            "custom_app_name_desc" to "The title displayed at the top of the app bar",
            "change_key_file" to "Change Security Key File",
            "change_key_file_desc" to "Change the key file required to open this vault",
            "change_key_file_success" to "Security key file updated successfully.",
            "protection_active" to "Protection Active",
            "protection_active_desc" to "All files are secured with military-grade AES-256 encryption.",
            "storage_usage" to "Storage: %1\$s used of %2\$s (%3\$d%%)",
            "vault_storage" to "Total secured files size: %1\$s",
            "sort_by_name" to "File Name",
            "sort_by_size" to "File Size",
            "sort_by_date" to "Added Date",
            "delete_confirm_title" to "Permanently Delete",
            "delete_confirm_desc" to "Are you absolutely sure you want to permanently delete these files? This action cannot be undone.",
            "delete_button" to "Delete Permanently",
            "cancel" to "Cancel",
            "import_files_title" to "Add Files to Vault",
            "import_select_button" to "Select Files",
            "import_storage_info" to "Available: %1\$s | Required: %2\$s",
            "import_insufficient_storage" to "Insufficient storage space!",
            "import_option_copy" to "Copy files (Original remains on device)",
            "import_option_move" to "Move files (Original is deleted securely)",
            "import_progress" to "Encrypting and moving files… %1\$d%%",
            "import_success" to "Files successfully encrypted and secured in vault.",
            "export_title" to "Export Files",
            "export_button" to "Decrypt & Save to Storage",
            "export_progress" to "Decrypting and restoring files… %1\$d%%",
            "export_success" to "Files decrypted and saved to Downloads/LUF folder.",
            "lang_label" to "Language / زبان برنامه",
            "lang_fa" to "فارسی",
            "lang_en" to "English",
            "app_info_title" to "LUF Vault Details",
            "app_info_desc" to "This secure container protects your sensitive documents. All metadata is stored offline, and physical payloads are double-wrapped via AES-256 with dynamic key bindings.",
            "prev_btn" to "Prev",
            "next_btn" to "Next"
        )
    )

    fun getString(lang: String, key: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }

    fun getString(lang: String, key: String, vararg args: Any): String {
        val format = getString(lang, key)
        return try {
            String.format(format, *args)
        } catch (e: Exception) {
            format
        }
    }
}
